### ISSUE TITLE
Please do not recompute all boundaries orientations every time a small edit is done on polygons

### ISSUE THREAD

**Issue by MichaelRamamonjisoa** [GuoxiaWang/InstanceLabelTool#2]
Hi, 

After drawing boundary polygons in the "instance" mode, and switching to "boundary" mode, the orientations appear, and I can flip them by clicking on them. This is great, since orientation are not always correct right after drawing the polygons. However, even if I save them, modifying or adding one polygon in the instance mode will then reset all the boundaries orientations. 

This is annoying since there might be a lot of boundaries which need flipping, and having to click on all of them at every edit feels tedious.

Anyway we could save a boundary orientation once its been edited in the "boundary" mode then edit only orientations of boundaries which have been added since last "boundary orientation edit" ?

**Comment by GuoxiaWang** [comment]
@MichaelRamamonjisoa 

Yes, I developed this tool using 1 week. So, this function does not support now. In the tool workflow, the first is to complete instance or polygon labeling, then you need to review the instance label, the third is to convert polygon to edges and corresponding orientation, the finally is to review the orientation. If you have a reviewed instance label, the orientations have few misconceptions.  

In my view, if you want to support modifying the orientation after modify the polygon label based this tool designed, it is a very complex and confusing thing. Because when you modify the polygon, it will lead to change the original edge connection every time.

So, I recommend you follow the workflow or open a  feature branch to support this function by yourself. 

Thank you!
